"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { toast } from "@/components/ui/use-toast"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import {
  FileSpreadsheet,
  Upload,
  X,
  RefreshCw,
  PlusCircle,
  FileText,
  AlertTriangle,
  Sparkles,
  BarChart3,
  TrendingUp,
  TrendingDown,
} from "lucide-react"

// Mock KPI data
const mockKpis = [
  {
    id: "kpi-1",
    name: "Monthly Recurring Revenue (MRR)",
    description: "Total predictable revenue generated from subscriptions on a monthly basis",
    target: 1000000,
    current: 945000,
    unit: "USD",
    format: "currency",
    period: "monthly",
    status: "on-track",
    trend: "up",
    trendValue: 8.2,
    category: "revenue",
  },
  {
    id: "kpi-2",
    name: "Customer Acquisition Cost (CAC)",
    description: "Average cost to acquire a new customer",
    target: 500,
    current: 450,
    unit: "USD",
    format: "currency",
    period: "monthly",
    status: "on-track",
    trend: "down",
    trendValue: 5.3,
    category: "marketing",
  },
  {
    id: "kpi-3",
    name: "Customer Lifetime Value (LTV)",
    description: "Average revenue generated by a customer over their lifetime",
    target: 5000,
    current: 4800,
    unit: "USD",
    format: "currency",
    period: "lifetime",
    status: "on-track",
    trend: "up",
    trendValue: 3.1,
    category: "customer",
  },
  {
    id: "kpi-4",
    name: "Churn Rate",
    description: "Percentage of customers who cancel their subscription in a given period",
    target: 2,
    current: 2.5,
    unit: "%",
    format: "percentage",
    period: "monthly",
    status: "at-risk",
    trend: "up",
    trendValue: 0.3,
    category: "customer",
  },
  {
    id: "kpi-5",
    name: "Gross Margin",
    description: "Percentage of revenue retained after direct costs",
    target: 75,
    current: 72,
    unit: "%",
    format: "percentage",
    period: "monthly",
    status: "at-risk",
    trend: "down",
    trendValue: 1.2,
    category: "financial",
  },
]

// Format value based on format type
const formatValue = (value: number, format: string, unit: string) => {
  if (format === "currency") {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      maximumFractionDigits: 0,
    }).format(value)
  } else if (format === "percentage") {
    return `${value}${unit}`
  } else {
    return `${value}${unit ? " " + unit : ""}`
  }
}

// Calculate progress percentage
const calculateProgress = (current: number, target: number) => {
  // For metrics where lower is better (like CAC, Churn)
  if (["Churn Rate", "Customer Acquisition Cost (CAC)"].includes(current.toString())) {
    return Math.min(100, Math.max(0, (target / current) * 100))
  }
  // For metrics where higher is better
  return Math.min(100, Math.max(0, (current / target) * 100))
}

// Get status color
const getStatusColor = (status: string) => {
  switch (status) {
    case "on-track":
      return "bg-emerald-500"
    case "at-risk":
      return "bg-amber-500"
    case "off-track":
      return "bg-rose-500"
    default:
      return "bg-slate-500"
  }
}

// Get trend icon and color
const getTrendIndicator = (trend: string, isPositive: boolean) => {
  if (trend === "up") {
    return {
      icon: <TrendingUp className={`h-4 w-4 ${isPositive ? "text-emerald-500" : "text-rose-500"}`} />,
      color: isPositive ? "text-emerald-500" : "text-rose-500",
    }
  } else {
    return {
      icon: <TrendingDown className={`h-4 w-4 ${isPositive ? "text-emerald-500" : "text-rose-500"}`} />,
      color: isPositive ? "text-emerald-500" : "text-rose-500",
    }
  }
}

// Determine if a trend is positive based on KPI name
const isTrendPositive = (kpiName: string, trend: string) => {
  // For these metrics, a downward trend is positive
  const downwardIsPositive = ["Customer Acquisition Cost", "CAC", "Churn Rate", "Burn Rate", "Cost per", "Expense"]

  const isDownwardPositive = downwardIsPositive.some((term) => kpiName.includes(term))

  return (trend === "up" && !isDownwardPositive) || (trend === "down" && isDownwardPositive)
}

interface KpiTrackingSectionProps {
  selectedPeriod: string
}

export function KpiTrackingSection({ selectedPeriod }: KpiTrackingSectionProps) {
  const [kpis, setKpis] = useState(mockKpis)
  const [uploadedFiles, setUploadedFiles] = useState<string[]>([])
  const [isUploading, setIsUploading] = useState(false)
  const [isProcessing, setIsProcessing] = useState(false)
  const [showAddKpiDialog, setShowAddKpiDialog] = useState(false)
  const [newKpi, setNewKpi] = useState({
    name: "",
    description: "",
    target: "",
    current: "",
    unit: "",
    period: "monthly",
    category: "financial",
  })
  const [kpiText, setKpiText] = useState("")
  const [activeTab, setActiveTab] = useState("all")

  // Handle file upload
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const newFiles = Array.from(e.target.files).map((file) => file.name)
      setUploadedFiles([...uploadedFiles, ...newFiles])
    }
  }

  // Remove file
  const removeFile = (fileName: string) => {
    setUploadedFiles(uploadedFiles.filter((file) => file !== fileName))
  }

  // Process uploaded files
  const processFiles = () => {
    if (uploadedFiles.length === 0) {
      toast({
        title: "No files selected",
        description: "Please select at least one file to upload.",
        variant: "destructive",
      })
      return
    }

    setIsUploading(true)

    // Simulate upload process
    setTimeout(() => {
      setIsUploading(false)
      setIsProcessing(true)

      // Simulate LLM processing
      setTimeout(() => {
        setIsProcessing(false)
        toast({
          title: "KPIs Processed Successfully",
          description: `${uploadedFiles.length} file(s) have been processed and KPIs extracted.`,
        })
        setUploadedFiles([])
      }, 3000)
    }, 1500)
  }

  // Process KPI text input
  const processKpiText = () => {
    if (!kpiText.trim()) {
      toast({
        title: "No KPI data provided",
        description: "Please enter KPI information to process.",
        variant: "destructive",
      })
      return
    }

    setIsProcessing(true)

    // Simulate LLM processing
    setTimeout(() => {
      setIsProcessing(false)
      toast({
        title: "KPIs Processed Successfully",
        description: "Your KPI data has been processed and added to the dashboard.",
      })
      setKpiText("")
    }, 3000)
  }

  // Add new KPI manually
  const addNewKpi = () => {
    if (!newKpi.name || !newKpi.target || !newKpi.current) {
      toast({
        title: "Missing required fields",
        description: "Please fill in all required fields.",
        variant: "destructive",
      })
      return
    }

    const kpiToAdd = {
      id: `kpi-${kpis.length + 1}`,
      name: newKpi.name,
      description: newKpi.description,
      target: Number.parseFloat(newKpi.target),
      current: Number.parseFloat(newKpi.current),
      unit: newKpi.unit,
      format: newKpi.unit === "%" ? "percentage" : "currency",
      period: newKpi.period,
      status: Number.parseFloat(newKpi.current) >= Number.parseFloat(newKpi.target) * 0.9 ? "on-track" : "at-risk",
      trend: "up",
      trendValue: 0,
      category: newKpi.category,
    }

    setKpis([...kpis, kpiToAdd])
    setShowAddKpiDialog(false)

    // Reset form
    setNewKpi({
      name: "",
      description: "",
      target: "",
      current: "",
      unit: "",
      period: "monthly",
      category: "financial",
    })

    toast({
      title: "KPI Added",
      description: "Your new KPI has been added to the dashboard.",
    })
  }

  // Filter KPIs by category
  const filteredKpis = activeTab === "all" ? kpis : kpis.filter((kpi) => kpi.category === activeTab)

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold">KPI Tracking</h2>
          <p className="text-muted-foreground">Monitor and analyze your key performance indicators</p>
        </div>
        <div className="flex gap-3">
          <Dialog>
            <DialogTrigger asChild>
              <Button>
                <Upload className="mr-2 h-4 w-4" />
                Upload KPIs
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[600px]">
              <DialogHeader>
                <DialogTitle>Upload KPI Data</DialogTitle>
                <DialogDescription>Upload files or paste KPI information to be processed by AI</DialogDescription>
              </DialogHeader>

              <Tabs defaultValue="upload" className="mt-4">
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="upload">Upload Files</TabsTrigger>
                  <TabsTrigger value="paste">Paste KPI Data</TabsTrigger>
                </TabsList>

                <TabsContent value="upload" className="space-y-4 mt-4">
                  <div className="border-2 border-dashed rounded-lg p-6 text-center">
                    <div className="flex flex-col items-center justify-center gap-4">
                      <div className="rounded-full bg-primary/10 p-4">
                        <Upload className="h-8 w-8 text-primary" />
                      </div>
                      <div>
                        <p className="font-medium">Drag files here or click to browse</p>
                        <p className="text-sm text-muted-foreground mt-1">
                          Supports CSV, Excel, and text files with KPI data
                        </p>
                      </div>
                      <div>
                        <Input id="file-upload" type="file" multiple className="hidden" onChange={handleFileUpload} />
                        <Button asChild>
                          <Label htmlFor="file-upload">Select Files</Label>
                        </Button>
                      </div>
                    </div>
                  </div>

                  {uploadedFiles.length > 0 && (
                    <div className="mt-4 space-y-3">
                      <h4 className="text-sm font-medium">Selected Files</h4>
                      {uploadedFiles.map((file, index) => (
                        <div key={index} className="flex items-center justify-between p-3 border rounded-lg">
                          <div className="flex items-center gap-3">
                            <div className="rounded-full bg-blue-500/20 p-2">
                              <FileSpreadsheet className="h-4 w-4 text-blue-500" />
                            </div>
                            <span className="text-sm font-medium">{file}</span>
                          </div>
                          <Button variant="ghost" size="icon" onClick={() => removeFile(file)}>
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="paste" className="space-y-4 mt-4">
                  <div className="space-y-2">
                    <Label htmlFor="kpi-text">Paste KPI Information</Label>
                    <Textarea
                      id="kpi-text"
                      placeholder="Paste your KPI data here. For example:
MRR: $945,000, Target: $1,000,000
CAC: $450, Target: $500
Churn Rate: 2.5%, Target: 2%
..."
                      rows={10}
                      value={kpiText}
                      onChange={(e) => setKpiText(e.target.value)}
                    />
                    <p className="text-xs text-muted-foreground">
                      Our AI will parse the KPI information and extract relevant metrics, targets, and current values.
                    </p>
                  </div>
                  <Button className="w-full" onClick={processKpiText} disabled={isProcessing || !kpiText.trim()}>
                    {isProcessing ? (
                      <>
                        <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <Sparkles className="mr-2 h-4 w-4" />
                        Process with AI
                      </>
                    )}
                  </Button>
                </TabsContent>
              </Tabs>

              <DialogFooter className="mt-6">
                <Button variant="outline" type="button">
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={isUploading || isProcessing || (uploadedFiles.length === 0 && !kpiText.trim())}
                  onClick={uploadedFiles.length > 0 ? processFiles : processKpiText}
                >
                  {isUploading ? (
                    <>
                      <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                      Uploading...
                    </>
                  ) : isProcessing ? (
                    <>
                      <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                      Processing with AI...
                    </>
                  ) : (
                    "Process KPIs"
                  )}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>

          <Dialog open={showAddKpiDialog} onOpenChange={setShowAddKpiDialog}>
            <DialogTrigger asChild>
              <Button variant="outline">
                <PlusCircle className="mr-2 h-4 w-4" />
                Add KPI Manually
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[500px]">
              <DialogHeader>
                <DialogTitle>Add New KPI</DialogTitle>
                <DialogDescription>Manually add a new KPI to track in your dashboard</DialogDescription>
              </DialogHeader>

              <div className="grid gap-4 py-4">
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-name" className="text-right">
                    Name*
                  </Label>
                  <Input
                    id="kpi-name"
                    placeholder="e.g., Monthly Recurring Revenue"
                    className="col-span-3"
                    value={newKpi.name}
                    onChange={(e) => setNewKpi({ ...newKpi, name: e.target.value })}
                  />
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-description" className="text-right">
                    Description
                  </Label>
                  <Textarea
                    id="kpi-description"
                    placeholder="Brief description of this KPI"
                    className="col-span-3"
                    value={newKpi.description}
                    onChange={(e) => setNewKpi({ ...newKpi, description: e.target.value })}
                  />
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-target" className="text-right">
                    Target*
                  </Label>
                  <Input
                    id="kpi-target"
                    type="number"
                    placeholder="Target value"
                    className="col-span-3"
                    value={newKpi.target}
                    onChange={(e) => setNewKpi({ ...newKpi, target: e.target.value })}
                  />
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-current" className="text-right">
                    Current*
                  </Label>
                  <Input
                    id="kpi-current"
                    type="number"
                    placeholder="Current value"
                    className="col-span-3"
                    value={newKpi.current}
                    onChange={(e) => setNewKpi({ ...newKpi, current: e.target.value })}
                  />
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-unit" className="text-right">
                    Unit
                  </Label>
                  <Input
                    id="kpi-unit"
                    placeholder="e.g., $, %, users"
                    className="col-span-3"
                    value={newKpi.unit}
                    onChange={(e) => setNewKpi({ ...newKpi, unit: e.target.value })}
                  />
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-period" className="text-right">
                    Period
                  </Label>
                  <select
                    id="kpi-period"
                    className="col-span-3 flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    value={newKpi.period}
                    onChange={(e) => setNewKpi({ ...newKpi, period: e.target.value })}
                  >
                    <option value="daily">Daily</option>
                    <option value="weekly">Weekly</option>
                    <option value="monthly">Monthly</option>
                    <option value="quarterly">Quarterly</option>
                    <option value="yearly">Yearly</option>
                    <option value="lifetime">Lifetime</option>
                  </select>
                </div>
                <div className="grid grid-cols-4 items-center gap-4">
                  <Label htmlFor="kpi-category" className="text-right">
                    Category
                  </Label>
                  <select
                    id="kpi-category"
                    className="col-span-3 flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    value={newKpi.category}
                    onChange={(e) => setNewKpi({ ...newKpi, category: e.target.value })}
                  >
                    <option value="financial">Financial</option>
                    <option value="revenue">Revenue</option>
                    <option value="marketing">Marketing</option>
                    <option value="customer">Customer</option>
                    <option value="product">Product</option>
                    <option value="operations">Operations</option>
                  </select>
                </div>
              </div>

              <DialogFooter>
                <Button variant="outline" onClick={() => setShowAddKpiDialog(false)}>
                  Cancel
                </Button>
                <Button onClick={addNewKpi}>Add KPI</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      <Tabs defaultValue="all" className="w-full" onValueChange={setActiveTab}>
        <TabsList className="mb-4">
          <TabsTrigger value="all">All KPIs</TabsTrigger>
          <TabsTrigger value="financial">Financial</TabsTrigger>
          <TabsTrigger value="revenue">Revenue</TabsTrigger>
          <TabsTrigger value="marketing">Marketing</TabsTrigger>
          <TabsTrigger value="customer">Customer</TabsTrigger>
        </TabsList>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
          {filteredKpis.slice(0, 3).map((kpi) => {
            const trendIsPositive = isTrendPositive(kpi.name, kpi.trend)
            const trendIndicator = getTrendIndicator(kpi.trend, trendIsPositive)

            return (
              <Card key={kpi.id}>
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-sm font-medium text-muted-foreground">{kpi.name}</CardTitle>
                    <Badge
                      className={`${
                        kpi.status === "on-track"
                          ? "bg-emerald-500/20 text-emerald-700"
                          : kpi.status === "at-risk"
                            ? "bg-amber-500/20 text-amber-700"
                            : "bg-rose-500/20 text-rose-700"
                      } hover:bg-opacity-20`}
                    >
                      {kpi.status === "on-track" ? "On Track" : kpi.status === "at-risk" ? "At Risk" : "Off Track"}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="text-2xl font-bold">{formatValue(kpi.current, kpi.format, kpi.unit)}</div>
                    <div className={`flex items-center font-medium text-sm ${trendIndicator.color}`}>
                      {trendIndicator.icon}
                      {kpi.trendValue}%
                    </div>
                  </div>
                  <div className="mt-2 space-y-1">
                    <div className="flex justify-between text-xs">
                      <span>Progress to target</span>
                      <span>
                        {formatValue(kpi.current, kpi.format, kpi.unit)} /{" "}
                        {formatValue(kpi.target, kpi.format, kpi.unit)}
                      </span>
                    </div>
                    <Progress
                      value={calculateProgress(kpi.current, kpi.target)}
                      className={`h-2 ${
                        kpi.status === "on-track"
                          ? "bg-emerald-100"
                          : kpi.status === "at-risk"
                            ? "bg-amber-100"
                            : "bg-rose-100"
                      }`}
                      indicatorClassName={
                        kpi.status === "on-track"
                          ? "bg-emerald-500"
                          : kpi.status === "at-risk"
                            ? "bg-amber-500"
                            : "bg-rose-500"
                      }
                    />
                  </div>
                  <p className="text-xs text-muted-foreground mt-2">{kpi.description}</p>
                </CardContent>
              </Card>
            )
          })}
        </div>

        <Card>
          <CardHeader>
            <CardTitle>KPI Dashboard</CardTitle>
            <CardDescription>Track and monitor all your key performance indicators</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="rounded-md border">
              <div className="grid grid-cols-7 border-b bg-muted/50 px-4 py-3 text-sm font-medium">
                <div className="col-span-2">KPI</div>
                <div className="col-span-1">Category</div>
                <div className="col-span-1 text-right">Current</div>
                <div className="col-span-1 text-right">Target</div>
                <div className="col-span-1 text-right">Progress</div>
                <div className="col-span-1 text-right">Status</div>
              </div>

              {filteredKpis.map((kpi) => {
                const trendIsPositive = isTrendPositive(kpi.name, kpi.trend)
                const trendIndicator = getTrendIndicator(kpi.trend, trendIsPositive)
                const progress = calculateProgress(kpi.current, kpi.target)

                return (
                  <div key={kpi.id} className="grid grid-cols-7 border-b px-4 py-3 text-sm">
                    <div className="col-span-2">
                      <div className="font-medium">{kpi.name}</div>
                      <div className="text-xs text-muted-foreground">{kpi.period}</div>
                    </div>
                    <div className="col-span-1 capitalize">{kpi.category}</div>
                    <div className="col-span-1 text-right">
                      <div className="font-medium">{formatValue(kpi.current, kpi.format, kpi.unit)}</div>
                      <div className={`flex items-center justify-end text-xs ${trendIndicator.color}`}>
                        {trendIndicator.icon}
                        <span className="ml-1">{kpi.trendValue}%</span>
                      </div>
                    </div>
                    <div className="col-span-1 text-right">{formatValue(kpi.target, kpi.format, kpi.unit)}</div>
                    <div className="col-span-1 text-right">
                      <div className="w-full bg-muted rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${getStatusColor(kpi.status)}`}
                          style={{ width: `${progress}%` }}
                        ></div>
                      </div>
                      <div className="text-xs mt-1">{Math.round(progress)}%</div>
                    </div>
                    <div className="col-span-1 text-right">
                      <Badge
                        className={`${
                          kpi.status === "on-track"
                            ? "bg-emerald-500/20 text-emerald-700"
                            : kpi.status === "at-risk"
                              ? "bg-amber-500/20 text-amber-700"
                              : "bg-rose-500/20 text-rose-700"
                        } hover:bg-opacity-20`}
                      >
                        {kpi.status === "on-track" ? "On Track" : kpi.status === "at-risk" ? "At Risk" : "Off Track"}
                      </Badge>
                    </div>
                  </div>
                )
              })}

              {filteredKpis.length === 0 && (
                <div className="px-4 py-6 text-center text-muted-foreground">
                  No KPIs found for this category. Add KPIs or change the filter.
                </div>
              )}
            </div>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button variant="outline">
              <FileText className="mr-2 h-4 w-4" />
              Export KPI Report
            </Button>
            <Button variant="outline" onClick={() => setShowAddKpiDialog(true)}>
              <PlusCircle className="mr-2 h-4 w-4" />
              Add New KPI
            </Button>
          </CardFooter>
        </Card>

        <Card className="mt-6 border-primary/20 bg-primary/5">
          <CardHeader>
            <CardTitle className="flex items-center">
              <Sparkles className="h-5 w-5 mr-2 text-primary" />
              AI KPI Analysis
            </CardTitle>
            <CardDescription>AI-generated insights based on your KPI performance</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="flex items-start gap-4 rounded-lg border p-4 bg-white">
              <div className="rounded-full bg-emerald-500/20 p-2">
                <TrendingUp className="h-4 w-4 text-emerald-500" />
              </div>
              <div>
                <h4 className="text-sm font-semibold">Strong MRR Growth Trend</h4>
                <p className="text-sm text-muted-foreground mt-1">
                  Your Monthly Recurring Revenue (MRR) is showing strong growth at 8.2% month-over-month, which puts you
                  on track to exceed your target within the next 2 months. This growth is primarily driven by enterprise
                  subscription increases, suggesting your recent enterprise sales strategy is effective.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-4 rounded-lg border p-4 bg-white">
              <div className="rounded-full bg-amber-500/20 p-2">
                <AlertTriangle className="h-4 w-4 text-amber-500" />
              </div>
              <div>
                <h4 className="text-sm font-semibold">Churn Rate Requires Attention</h4>
                <p className="text-sm text-muted-foreground mt-1">
                  Your Churn Rate is currently at 2.5%, which is 0.5 percentage points above your target of 2%. Analysis
                  of customer feedback suggests that price sensitivity in the SMB segment is increasing. Consider
                  implementing a customer success program focused on demonstrating ROI to at-risk SMB customers.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-4 rounded-lg border p-4 bg-white">
              <div className="rounded-full bg-emerald-500/20 p-2">
                <BarChart3 className="h-4 w-4 text-emerald-500" />
              </div>
              <div>
                <h4 className="text-sm font-semibold">CAC Efficiency Improving</h4>
                <p className="text-sm text-muted-foreground mt-1">
                  Your Customer Acquisition Cost (CAC) has decreased by 5.3% to $450, which is below your target of
                  $500. This improvement in acquisition efficiency appears to be correlated with your recent shift to
                  account-based marketing for enterprise customers. The LTV:CAC ratio is now at 10.7:1, which is well
                  above the industry benchmark of 3:1.
                </p>
              </div>
            </div>
          </CardContent>
          <CardFooter>
            <Button variant="outline" className="w-full">
              <Sparkles className="mr-2 h-4 w-4" />
              Generate Comprehensive KPI Analysis
            </Button>
          </CardFooter>
        </Card>
      </Tabs>
    </div>
  )
}
